---
ID: "49c91ba3-3f61-4af9-91ce-9a9cb7a51035"
Parent: "dc8f6a75-2c37-493d-b12b-4173d3fd1950"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Weekly Fitness Report Signup/Page/Section/RunningTypeSection/RunningType/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181023T194054Z
