---
ID: "f5b342fd-c7b1-4743-be36-6b675c2bd859"
Parent: "5c91ead1-11f3-4c75-8a61-e020359ffcc0"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Weekly Fitness Report Signup/Page/Section/CyclingTypeSection/CyclingType/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181023T194433Z
